version: '3.8'
services:
  database:
    container_name: database
    image: postgres:16.1-alpine
    restart: always
    ports:
      - '${DATABASE_PORT}:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nextjs
    volumes:
      - database-volume:/var/lib/postgresql/data
  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      # Change the number before : to the port the web interface should be accessible on
      - '5001:80'
      # Change the number before : to the port the SMTP server should be accessible on
      - '25:25'
    volumes:
      - smtp4dev-data:/smtp4dev
volumes:
  database-volume:
  smtp4dev-data:
