#####
# Documentation
# YAML (all config values): https://render.com/docs/yaml-spec
#####
previewsEnabled: true
services:
  - name: nextjs-template
    type: web
    plan: free
    env: node
    region: frankfurt
    healthCheckPath: /api/health
    buildCommand: yarn && yarn build
    startCommand: yarn prisma:migrate:prod && yarn start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nextjs-template-db
          property: connectionString

databases:
  - name: nextjs-template-db
    plan: free
    region: frankfurt
