import { Button } from '@chakra-ui/react'
import type { NextPage } from 'next'
import { GetServerSidePropsContext } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { getToken } from 'next-auth/jwt'
import { signOut } from 'next-auth/react'
import { Route } from 'constants/common/routes'

const Home: NextPage = () => (
  <div>
    <Head>
      <title>appName</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <p>Home</p>
    <Link passHref href={Route.Admin}>
      <Button>admin:page.title</Button>
    </Link>
    <Link passHref href={Route.Member}>
      <Button>member:page.title</Button>
    </Link>
    <Button
      onClick={() => {
        void (() => signOut())()
      }}
    >
      logOut
    </Button>
  </div>
)

export const getServerSideProps = async (context: GetServerSidePropsContext) => {
  const token = await getToken({ req: context.req })
  if (!token) {
    return {
      redirect: {
        destination: Route.SignIn,
        permanent: false,
      },
    }
  }
  return {
    props: {},
  }
}

export default Home
