import type { NextPage } from 'next'
import { GetServerSidePropsContext } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { getToken } from 'next-auth/jwt'
import { signOut } from 'next-auth/react'
import { useTranslation } from 'next-i18next'
import { Route } from 'constants/common/routes'
import { Button } from 'components/ui/button'
import { serverSideTranslations } from 'utils/i18n'

const Home: NextPage = () => {
  const { t } = useTranslation(['common', 'admin', 'hello', 'member'])
  return (
    <div>
      <Head>
        <title>{t('appName')}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>{t('Home')}</p>
      <Link passHref href={Route.Admin}>
        <Button>{t('admin:page.title')}</Button>
      </Link>
      <Link passHref href={Route.Member}>
        <Button>{t('member:page.title')}</Button>
      </Link>
      <Button
        onClick={() => {
          void (() => signOut())()
        }}
      >
        {t('logOut')}
      </Button>
    </div>
  )
}

export const getServerSideProps = async (context: GetServerSidePropsContext) => {
  const token = await getToken({ req: context.req })
  if (!token) {
    return {
      redirect: {
        destination: Route.SignIn,
        permanent: false,
      },
    }
  }
  return {
    props: {
      ...(await serverSideTranslations(context, ['admin', 'common', 'hello', 'member'])),
    },
  }
}

export default Home
